FROM rocker/shiny-verse:4.3.0

RUN apt-get update -qq && apt-get -y --no-install-recommends install     libxml2-dev     libcairo2-dev     libsqlite3-dev     libpq-dev     libssh2-1-dev     unixodbc-dev     libcurl4-openssl-dev     libssl-d>
RUN apt-get update &&     apt-get upgrade -y &&     apt-get clean

RUN apt-get update
RUN apt-get install -y git
RUN apt install -y cmake
RUN apt install -y build-essential

COPY /imputomics/inst/Imputomics ./imputomics
COPY /imputomics/renv.lock ./

RUN ulimit -n 8192

RUN R -e "Sys.setenv(RENV_DOWNLOAD_METHOD = 'libcurl'); Sys.setenv('RENV_CONFIG_REPOS_OVERRIDE' = 'http://cran.rstudio.com'); install.packages('renv'); options(renv.consent = TRUE); install.packages(c('markdo>
EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/imputomics', host = '0.0.0.0', port = 3838)"]
